-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Tutor" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
